name: flutter_ps5_library
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  date_format: ^2.0.7
  flutter_widget_from_html_core: ^0.14.11
  go_router: ^13.2.0
  http: ^1.2.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true